### ISSUE TITLE
The Documentation site is down(error code:404)

### ISSUE THREAD

**Issue by JackLau1222** [OpenTenBase/docs#10]
the documentation site in README.md is down,I can't visit it,and it returns 404 error code
<img width="1146" alt="image" src="https://github.com/OpenTenBase/docs/assets/131463945/4b3b66a3-461d-4036-8928-f3b131ea2a3d">

**Comment by bartdong** [comment]
Thank you for reporting this error. It's ok now.
It is down because of the bug of using two custom domains at the same time on the GitHub page.
